development:
  adapter: postgresql
  encoding: unicode
  database: IHeartQuotes_development
  pool: 5
  username: Jean
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: IHeartQuotes_test
  pool: 5
  username: Jean
  password:

cucumber:
  <<: *test
